language: node_js

node_js:
  - "stable"

notifications:
  email: false

env:
  global:
    - CC_TEST_REPORTER_ID=1e465e9084eaa5f9056254a37a1681510c3527466bb52f74dd7708783c62de01
    - TRAVIS_HOST=127.0.0.1
    - TRAVIS_USER=johnson
    - TRAVIS_DATABASE=travis_ci_test
    - TRAVIS_PASSWORD=abc123
    - TRAVIS_PORT=5432
    - NODE_ENV=test

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - psql -c "CREATE USER johnson WITH PASSWORD 'abc123';" -U postgres
  - npm install nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov --reporter=text-lcov npm test

after_success:
  npm run coverage