language: node_js
node_js:
  - "stable"
before_script:
 # - psql -c 'create database travis;' -U postgres
script: 
 # - "npm run-script migration"
  - "npm run-script test-travis"
 
  
# send coverage data to coveralls
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage